apiVersion: v1
kind: Pod
metadata:
  name: dhlapp1
  labels:
    app: dhlapp1
spec:
  containers:
  - image: docker.io/stv707/dhlapp1:v1 
    name: appred
    volumeMounts:
    - name: config
      mountPath: /data
      readOnly: true
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  volumes:
  - name: config
    configMap:
      name: dhlconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: dhlapp1
spec:
  selector:
    app: dhlapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
