apiVersion: v1
kind: Pod
metadata:
  name: dhlapp2
  labels:
    app: dhlapp2
spec:
  containers:
  - image: docker.io/stv707/dhlapp2:v1 
    name: appblue
    volumeMounts:
    - name: config
      mountPath: /data
      readOnly: true
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  volumes:
  - name: config
    configMap:
      name: dhlconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: dhlapp2
spec:
  selector:
    app: dhlapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
